server:
  host: "0.0.0.0"
  port: 3000

database:
  # URL will be overridden by environment variable
  url: "postgresql://postgres:postgres@postgres:5432/cherryserver"
  max_connections: 50
  min_connections: 5

jwt:
  # Secret will be overridden by environment variable
  secret: "production-secret-override-via-env"
  expiration_hours: 24

logging:
  level: "warn"
