server:
  host: "0.0.0.0"
  port: 3000

database:
  url: "postgresql://postgres:password@localhost/mydb"
  max_connections: 10
  min_connections: 1

jwt:
  secret: "my-super-secret-jwt-key-for-production"
  expiration_hours: 24

logging:
  level: "info"
