server:
  host: "0.0.0.0"
  port: 3000

database:
  url: "postgresql://postgres:postgres123@postgres:5432/cherryserver"
  max_connections: 20
  min_connections: 2

jwt:
  secret: "docker-jwt-secret-change-in-production"
  expiration_hours: 24

logging:
  level: "info"
