# Development environment overrides
# This file is automatically merged with docker-compose.yml when running `docker-compose up`

version: '3.8'

services:
  cherryserver:
    environment:
      # Development specific settings
      CHERRYSERVER_LOGGING__LEVEL: "debug"
      RUST_LOG: "debug"
      RUST_BACKTRACE: "1"
    volumes:
      # Mount source code for development (if using a dev image)
      # - ./crates/cherryserver/src:/app/src:ro
      # Mount config file for easy editing
      - ./config-docker.yaml:/app/config.yaml:ro
    # Uncomment for development with live reload
    # command: ["cargo", "watch", "-x", "run"]
    
  postgres:
    environment:
      # Development database settings
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"  # Expose database port for development tools
    volumes:
      # Add development database scripts
      - ./docker/dev-data.sql:/docker-entrypoint-initdb.d/99-dev-data.sql:ro

  # Enable pgAdmin in development by default
  pgadmin:
    profiles: []  # Remove the 'admin' profile to enable by default 