
services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: cherryserver-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cherryserver
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
  # PostgresSql for fileserver
  fileserver-postgres:
    image: postgres:15-alpine
    container_name: fileserver-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fileserver
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"

  # Optional: PostgreSQL Admin (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cherryserver-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cherryserver.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8099:80"
    depends_on:
      - postgres
  mailcrab:
    image: marlonb/mailcrab:latest
    ports:
      - "1080:1080"
      
  rauthy:
    container_name: rauthy-test
    image: ghcr.io/sebadob/rauthy:0.30.2
    environment:
      - LOCAL_TEST=true
      - SMTP_URL=mailcrab
      - SMTP_PORT=1025
      - SMTP_DANGER_INSECURE=true
    ports:
      - "8443:8443"
    depends_on:
      - mailcrab